/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrainerWorkoutsRouteImport } from './routes/trainer.workouts'
import { Route as TrainerSettingsRouteImport } from './routes/trainer.settings'
import { Route as TrainerReportsRouteImport } from './routes/trainer.reports'
import { Route as TrainerPaymentsRouteImport } from './routes/trainer.payments'
import { Route as TrainerMeasurementsRouteImport } from './routes/trainer.measurements'
import { Route as TrainerMealsRouteImport } from './routes/trainer.meals'
import { Route as TrainerGoalsRouteImport } from './routes/trainer.goals'
import { Route as TrainerFeedbackRouteImport } from './routes/trainer.feedback'
import { Route as TrainerClientsRouteImport } from './routes/trainer.clients'
import { Route as TrainerAttendanceRouteImport } from './routes/trainer.attendance'
import { Route as ClientSettingsRouteImport } from './routes/client.settings'
import { Route as ClientProgressRouteImport } from './routes/client.progress'
import { Route as ClientPaymentsRouteImport } from './routes/client.payments'
import { Route as ClientMealsRouteImport } from './routes/client.meals'
import { Route as ClientGoalsRouteImport } from './routes/client.goals'
import { Route as AdminTrainersRouteImport } from './routes/admin.trainers'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'

const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrainerWorkoutsRoute = TrainerWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerSettingsRoute = TrainerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerReportsRoute = TrainerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerPaymentsRoute = TrainerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerMeasurementsRoute = TrainerMeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerMealsRoute = TrainerMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerGoalsRoute = TrainerGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerFeedbackRoute = TrainerFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerClientsRoute = TrainerClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerAttendanceRoute = TrainerAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TrainerRoute,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProgressRoute = ClientProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPaymentsRoute = ClientPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ClientRoute,
} as any)
const ClientMealsRoute = ClientMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => ClientRoute,
} as any)
const ClientGoalsRoute = ClientGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => ClientRoute,
} as any)
const AdminTrainersRoute = AdminTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/client/goals': typeof ClientGoalsRoute
  '/client/meals': typeof ClientMealsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/progress': typeof ClientProgressRoute
  '/client/settings': typeof ClientSettingsRoute
  '/trainer/attendance': typeof TrainerAttendanceRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/feedback': typeof TrainerFeedbackRoute
  '/trainer/goals': typeof TrainerGoalsRoute
  '/trainer/meals': typeof TrainerMealsRoute
  '/trainer/measurements': typeof TrainerMeasurementsRoute
  '/trainer/payments': typeof TrainerPaymentsRoute
  '/trainer/reports': typeof TrainerReportsRoute
  '/trainer/settings': typeof TrainerSettingsRoute
  '/trainer/workouts': typeof TrainerWorkoutsRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/client/goals': typeof ClientGoalsRoute
  '/client/meals': typeof ClientMealsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/progress': typeof ClientProgressRoute
  '/client/settings': typeof ClientSettingsRoute
  '/trainer/attendance': typeof TrainerAttendanceRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/feedback': typeof TrainerFeedbackRoute
  '/trainer/goals': typeof TrainerGoalsRoute
  '/trainer/meals': typeof TrainerMealsRoute
  '/trainer/measurements': typeof TrainerMeasurementsRoute
  '/trainer/payments': typeof TrainerPaymentsRoute
  '/trainer/reports': typeof TrainerReportsRoute
  '/trainer/settings': typeof TrainerSettingsRoute
  '/trainer/workouts': typeof TrainerWorkoutsRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/trainer': typeof TrainerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/client/goals': typeof ClientGoalsRoute
  '/client/meals': typeof ClientMealsRoute
  '/client/payments': typeof ClientPaymentsRoute
  '/client/progress': typeof ClientProgressRoute
  '/client/settings': typeof ClientSettingsRoute
  '/trainer/attendance': typeof TrainerAttendanceRoute
  '/trainer/clients': typeof TrainerClientsRoute
  '/trainer/feedback': typeof TrainerFeedbackRoute
  '/trainer/goals': typeof TrainerGoalsRoute
  '/trainer/meals': typeof TrainerMealsRoute
  '/trainer/measurements': typeof TrainerMeasurementsRoute
  '/trainer/payments': typeof TrainerPaymentsRoute
  '/trainer/reports': typeof TrainerReportsRoute
  '/trainer/settings': typeof TrainerSettingsRoute
  '/trainer/workouts': typeof TrainerWorkoutsRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/signup'
    | '/trainer'
    | '/admin/approvals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/trainers'
    | '/client/goals'
    | '/client/meals'
    | '/client/payments'
    | '/client/progress'
    | '/client/settings'
    | '/trainer/attendance'
    | '/trainer/clients'
    | '/trainer/feedback'
    | '/trainer/goals'
    | '/trainer/meals'
    | '/trainer/measurements'
    | '/trainer/payments'
    | '/trainer/reports'
    | '/trainer/settings'
    | '/trainer/workouts'
    | '/admin/'
    | '/client/'
    | '/trainer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/approvals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/trainers'
    | '/client/goals'
    | '/client/meals'
    | '/client/payments'
    | '/client/progress'
    | '/client/settings'
    | '/trainer/attendance'
    | '/trainer/clients'
    | '/trainer/feedback'
    | '/trainer/goals'
    | '/trainer/meals'
    | '/trainer/measurements'
    | '/trainer/payments'
    | '/trainer/reports'
    | '/trainer/settings'
    | '/trainer/workouts'
    | '/admin'
    | '/client'
    | '/trainer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/signup'
    | '/trainer'
    | '/admin/approvals'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/trainers'
    | '/client/goals'
    | '/client/meals'
    | '/client/payments'
    | '/client/progress'
    | '/client/settings'
    | '/trainer/attendance'
    | '/trainer/clients'
    | '/trainer/feedback'
    | '/trainer/goals'
    | '/trainer/meals'
    | '/trainer/measurements'
    | '/trainer/payments'
    | '/trainer/reports'
    | '/trainer/settings'
    | '/trainer/workouts'
    | '/admin/'
    | '/client/'
    | '/trainer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  TrainerRoute: typeof TrainerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/trainer/workouts': {
      id: '/trainer/workouts'
      path: '/workouts'
      fullPath: '/trainer/workouts'
      preLoaderRoute: typeof TrainerWorkoutsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/settings': {
      id: '/trainer/settings'
      path: '/settings'
      fullPath: '/trainer/settings'
      preLoaderRoute: typeof TrainerSettingsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/reports': {
      id: '/trainer/reports'
      path: '/reports'
      fullPath: '/trainer/reports'
      preLoaderRoute: typeof TrainerReportsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/payments': {
      id: '/trainer/payments'
      path: '/payments'
      fullPath: '/trainer/payments'
      preLoaderRoute: typeof TrainerPaymentsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/measurements': {
      id: '/trainer/measurements'
      path: '/measurements'
      fullPath: '/trainer/measurements'
      preLoaderRoute: typeof TrainerMeasurementsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/meals': {
      id: '/trainer/meals'
      path: '/meals'
      fullPath: '/trainer/meals'
      preLoaderRoute: typeof TrainerMealsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/goals': {
      id: '/trainer/goals'
      path: '/goals'
      fullPath: '/trainer/goals'
      preLoaderRoute: typeof TrainerGoalsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/feedback': {
      id: '/trainer/feedback'
      path: '/feedback'
      fullPath: '/trainer/feedback'
      preLoaderRoute: typeof TrainerFeedbackRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/clients': {
      id: '/trainer/clients'
      path: '/clients'
      fullPath: '/trainer/clients'
      preLoaderRoute: typeof TrainerClientsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/attendance': {
      id: '/trainer/attendance'
      path: '/attendance'
      fullPath: '/trainer/attendance'
      preLoaderRoute: typeof TrainerAttendanceRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/progress': {
      id: '/client/progress'
      path: '/progress'
      fullPath: '/client/progress'
      preLoaderRoute: typeof ClientProgressRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/payments': {
      id: '/client/payments'
      path: '/payments'
      fullPath: '/client/payments'
      preLoaderRoute: typeof ClientPaymentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/meals': {
      id: '/client/meals'
      path: '/meals'
      fullPath: '/client/meals'
      preLoaderRoute: typeof ClientMealsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/goals': {
      id: '/client/goals'
      path: '/goals'
      fullPath: '/client/goals'
      preLoaderRoute: typeof ClientGoalsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/trainers': {
      id: '/admin/trainers'
      path: '/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AdminTrainersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrainersRoute: typeof AdminTrainersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrainersRoute: AdminTrainersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientGoalsRoute: typeof ClientGoalsRoute
  ClientMealsRoute: typeof ClientMealsRoute
  ClientPaymentsRoute: typeof ClientPaymentsRoute
  ClientProgressRoute: typeof ClientProgressRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientGoalsRoute: ClientGoalsRoute,
  ClientMealsRoute: ClientMealsRoute,
  ClientPaymentsRoute: ClientPaymentsRoute,
  ClientProgressRoute: ClientProgressRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface TrainerRouteChildren {
  TrainerAttendanceRoute: typeof TrainerAttendanceRoute
  TrainerClientsRoute: typeof TrainerClientsRoute
  TrainerFeedbackRoute: typeof TrainerFeedbackRoute
  TrainerGoalsRoute: typeof TrainerGoalsRoute
  TrainerMealsRoute: typeof TrainerMealsRoute
  TrainerMeasurementsRoute: typeof TrainerMeasurementsRoute
  TrainerPaymentsRoute: typeof TrainerPaymentsRoute
  TrainerReportsRoute: typeof TrainerReportsRoute
  TrainerSettingsRoute: typeof TrainerSettingsRoute
  TrainerWorkoutsRoute: typeof TrainerWorkoutsRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerAttendanceRoute: TrainerAttendanceRoute,
  TrainerClientsRoute: TrainerClientsRoute,
  TrainerFeedbackRoute: TrainerFeedbackRoute,
  TrainerGoalsRoute: TrainerGoalsRoute,
  TrainerMealsRoute: TrainerMealsRoute,
  TrainerMeasurementsRoute: TrainerMeasurementsRoute,
  TrainerPaymentsRoute: TrainerPaymentsRoute,
  TrainerReportsRoute: TrainerReportsRoute,
  TrainerSettingsRoute: TrainerSettingsRoute,
  TrainerWorkoutsRoute: TrainerWorkoutsRoute,
  TrainerIndexRoute: TrainerIndexRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  TrainerRoute: TrainerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
